#!/usr/bin/env bash
minikube start --namespace rhdm --driver=hyperkit --memory 5120 --cpus 4 #--mount --mount-string="../pv:/data"
eval $(minikube docker-env)
open --background -a Docker &&
  while ! docker system info > /dev/null 2>&1; do sleep 1; done &&
cd dc
docker build --tag rhdm-decisioncentral:1 .
cd ../ds
docker build --tag rhdm-decisionserver:1 .
cd ..
osascript -e 'quit app "Docker"'
kubectl create -f rhdm.json
kubectl create secret generic decision-secret \
	--from-literal=KIE_ADMIN_USER=${DEMO_DM_ADMIN_USR} \
	--from-literal=KIE_ADMIN_PWD=${DEMO_DM_ADMIN_PWD}
kubectl create secret generic maven-secret \
	--from-literal=MAVEN_REPO_ID=${DEMO_MAVEN_ID} \
	--from-literal=MAVEN_REPO_URL=${DEMO_MAVEN_URL} \
	--from-literal=MAVEN_REPO_USERNAME=${DEMO_MAVEN_USR} \
	--from-literal=MAVEN_REPO_PASSWORD=${DEMO_MAVEN_PWD}
kubectl create -f decision.yaml 
sleep 30
kubectl get pods
dcpodname=$(kubectl get pods -o name --no-headers | grep decisioncentral)
kubectl exec $dcpodname -- mkdir -p /opt/kie/data/git/hooks
kubectl cp etc/post-commit $dcpodname:/opt/kie/data/git/hooks
kubectl get pods
echo "minikube ip"
minikube ip
