#!/usr/bin/env bash
kubectl create secret generic decisioncentral-secret \
	--from-literal=KIE_ADMIN_USER=${DEMO_DM_ADMIN_USR} \
	--from-literal=KIE_ADMIN_PWD=${DEMO_DM_ADMIN_PWD}
kubectl create secret generic maven-secret \
	--from-literal=MAVEN_REPO_ID=${DEMO_MAVEN_ID} \
	--from-literal=MAVEN_REPO_URL=${DEMO_MAVEN_URL} \
	--from-literal=MAVEN_REPO_USERNAME=${DEMO_MAVEN_USR} \
	--from-literal=MAVEN_REPO_PASSWORD=${DEMO_MAVEN_PWD}
